codecov:
  require_ci_to_pass: yes

coverage:
  precision: 3
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: 75%
        threshold: 10%
        base: auto
        only_pulls: false
        if_ci_failed: error
    patch: yes
    changes: no